name: Build and Deploy Custom Application Connector

on:
  push:
    branches:
      - development  # Specify the branch to trigger the workflow

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # Use your required Node.js version

      - name: Install dependencies
        run: npm install --legacy-peer-deps # or yarn install

      - name: Build application
        run: npm run build  # Adjust as necessary

      - name: Deploy to Commerce Tools
        env:
          CT_API_TOKEN: ${{ secrets.CT_API_TOKEN }}  # Set your API token in secrets
        run: |
          curl -X POST \
            https://auth.us-central1.gcp.commercetools.com/oauth/token \
            --basic --user "XtWafEB2FsR7kYyA2BAunjb3:mODT1ZVCIt57zSiccijcDhdTP6BkQKFp" \
            -d "grant_type=client_credentials&scope=manage_project:merchent-center-poc"